### ISSUE TITLE
Design new Bootstrapping Procedure

### ISSUE THREAD

**Issue by warp1337** [RDTK/organization#4]
The current docs at toolkit.cit-ec.de reference an outdated version of the jenkins.tar.gz. Also, the newer release, which is served but the cse jenkins, contains a generator version that reports an 'off by one' version number. Please let me know when the latter is fixed. I will then come up with a solution for the url and the link in the toolkit.cit-ec.de docs.

@scymtym

**Comment by scymtym** [comment]
> Also, the newer release, which is served but the cse jenkins, contains a generator version that reports an 'off by one' version number. Please let me know when the latter is fixed.

This is fixed and the issue should disappear once the changes propagate everywhere.

**Comment by warp1337** [comment]
We have a few options:

a) use travis in order to generate an archive and publish in new repo, e.g, RDTK/jenkins_distro
b) use the generator (if I understood correctly)
c) just shorten some urls

**Comment by scymtym** [comment]
> use travis in order to generate an archive and publish in new repo, e.g, RDTK/jenkins_distro

I think that these concerns are independent:
* How do we build the archive (python script vs. `build-generator install-jenkins`)
* Where do we build the archive (travis vs. bob)
* Where do we host the archive (GitHub release in new project vs. bob vs. ?)

**Comment by warp1337** [comment]
> > use travis in order to generate an archive and publish in new repo, e.g, RDTK/jenkins_distro
> 
> I think that these concerns are independent:
> 
>     * How do we build the archive (python script vs. `build-generator install-jenkins`)
> 
I'd say build-gen since this can then be used independently at some point
>     * Where do we build the archive (travis vs. bob)
> 
Travis, since bob might be wiped at some point, isn't this the dedicated use case?
>     * Where do we host the archive (GitHub release in new project vs. bob vs. ?)
GitHub IMHO

**Comment by scymtym** [comment]
OK, so assuming we create another repository RDTK/jenkins-distribution (or starter-kit or something like that), the actual process could look like this:

1. A travis job builds the generator binary.

2. The binary is uploaded as a release in the RDTK/generator repository.

   Caveat: I don't think there are release aliases such as "current" or "latest", but i may be wrong.

3. A Travis job for RDTK/jenkins-distribution downloads the generator binary and uses it to build the `jenkins.tar.gz` archive.

4. The archive is uploaded as a release in the RDTK/jenkins-distribution repository.

5. The documentation links to this release.

   Caveat: If there are no release aliases, this link would have to be updated for each new release.

**Comment by scymtym** [comment]
After addressing rdtk/generator#5, the workflow described in the previous comment should be implementable now.

There would be a slight difference in user experience. Users currently do

```shell
tar -xzf jenins.tar.gz
cd jenkins
./create_user.sh
[Prompts for username, email and password]
./start_jenkins
```

With the new workflow, users would have to execute the following commands:

```shell
tar -xzf jenins.tar.gz
cd jenkins
./build-generator install-jenkins --username=USERNAME --email=EMAIL --password=PASSWORD .
./start_jenkins
```

This might be confusing since `install-jenkins` actually means "create a user" in this case.

To improve this, we could either create a new `create_user.sh` that invokes the generator behind the scenes or add a `create-user` command to the generator.

**Comment by warp1337** [comment]
if its documented properly, I dont think this will be a problem.

**Comment by scymtym** [comment]
> if its documented properly, I dont think this will be a problem.

True.

However, while working on the `install-jenkins` command, I wondered whether users might want to use certain parts of what the command does in isolation. For example:

* Automatically add user accounts to a Jenkins installation

* Install Jenkins plugins required by a newer generator version to an old Jenkins installation without starting from scratch

* Update the configuration of an existing Jenkins installation for a new generator version (think warnings parsers)

**Comment by scymtym** [comment]
See [summary of possible bootstrapping strategies](https://github.com/RDTK/organization/wiki/2019-03-11#bootstrapping) in wiki

**Comment by scymtym** [comment]
In the meantime, we tried the generator-based strategy in a few instances and it worked pretty well.

Most people who had an opinion on this preferred the generator-based strategy as the primary way of bootstrapping.

It was pointed out that the archive-based strategy could still be useful for less common scenarios like preparing USB sticks for participants of a workshop.

All things considered, I lean towards declaring the generator-based strategy the default and closing this issue.

**Comment by scymtym** [comment]
Using `build-generator install-jenkins` for bootstrapping seems to be good enough for now (and is the method described in the new documentation).
